### ISSUE TITLE
Segfault with custom config-path on debian stretch

### ISSUE THREAD

**Issue by richardhuxton** [lxc/python2-lxc#16]
You can set an alternative default path in `/etc/lxc/lxc.conf` and it will pick that up and use it. You can specify a path for `list_containers()` and that works too. If you try to create a `Container` object then you get a segmentation fault. The value you provide for the path makes no difference (can be '/var/lib/lxc' or '/foo/bar').

I tested this as root.

The Python 3 version of this library works OK.

I could reproduce this with the debian package and installing via pip (which compiled against liblxc1 headers). Also with the package on ubuntu 18.04

Apologies for not providing a patch but Python is not my area of expertise and my guess is that this lies somewhere in the binding of the pathname to the C library.

```
# python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxc
>>> lxc.list_containers(config_path='/var/lib/lxc')
(u'elm', u'jessie-0', u'munin-test')
>>> c1=lxc.Container(name=u'elm')
>>> c2=lxc.Container(name=u'elm', config_path=u'/var/lib/lxc')
Segmentation fault
```

**Comment by stgraber** [comment]
With python2 now being end of life, we will not be doing any further development on python2-lxc.
