### ISSUE TITLE
python2-lxc cannot be installed on MacOS

### ISSUE THREAD

**Issue by ssbarnea** [lxc/python2-lxc#17]
At this moment it seems impossible to install python2-lxc on MacOS because there is no brew package that would install the header files needed by the package.

The lxc package does not contain them https://github.com/Homebrew/brew/issues/5326#event-1972060100 

Another alternative would be to start bulding and publishign binary wheels.

**Comment by stgraber** [comment]
With python2 now being end of life, we will not be doing any further development on python2-lxc.
