### ISSUE TITLE
Could you please branch the project?

### ISSUE THREAD

**Issue by ptloo** [lxc/python2-lxc#3]
Right now there is only one master branch. If the code is stable enough, is it possible for you to branch it like the python3 module? The reason is that I need a stable deployment process to ping to a specific version/branch. Many thanks!

**Comment by stgraber** [comment]
There is no guarantee of stability for the python2-lxc binding, only the python3 binding is fully supported and comes with multi-year bugfix releases.

**Comment by stgraber** [comment]
To clarify a bit, the python2-lxc module was quickly put together to satisfy a very specific need at the time by the OpenStack community to have a python2 module until they were ready to switch to python3.

Nowadays, we have an alternative for that specific case through LXD and so interest in keeping this module up to date and stable is very low and we'll deprecate it entirely soon if nobody steps up to actively maintain it.
