### ISSUE TITLE
set_config_item always appends

### ISSUE THREAD

**Issue by raharper** [lxc/python2-lxc#4]
Invoking set_config_item appears to always append values rather than updating a matching key.

Once can recreate this with:

    import lxc, subprocess
    container = lxc.Container('foo')
    container.set_config_path("/tmp")
    subprocess.check_call("mkdir -p /tmp/foo".split())
    subprocess.check_call("touch /tmp/foo/config".split())
    container.set_config_item('lxc.utsname', 'foo')
    container.set_config_item('lxc.utsname', 'bar')
    container.save_config()
    print subprocess.check_output("cat /tmp/foo/config".split())

Expect that config contain only:

    lxc.utsname = foo

Actual Output:

    lxc.utsname = foo
    lxc.utsname = bar

**Comment by stgraber** [comment]
Yep, it's a known issue of how lxc tracks local overrides of inherited configs.

Note that the parse will do the right thing, so while this results in an ugly config, the container will work as expected.

(Closing this issue as it's an LXC issue, not one with the binding).
