### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by leonty** [lxc/python2-lxc#5]
Please, make it available on the pypi platform. As this is the official binding for python2 other projects as Ansible use it (for lxc_container module), but there's no way just to make it all work out of the box. No way to include this library as a dependency for apt or pip.
Thanks.

**Comment by sebalix** [comment]
+1 I was also facing this problem with Ansible.

**Comment by stgraber** [comment]
Feel free to upload it to pypi yourself, as far as upstream is concerned the python2 module is an unsupported binding which we intend to deprecate in the very near future (it was a one time hack to get OpenStack support, but we've since moved to LXD for that).

**Comment by leonty** [comment]
What is the licence for the project? It's no indicated in the sources...

**Comment by stgraber** [comment]
It's declared in the file headers, LGPLv2.1+

**Comment by stgraber** [comment]
Looks like someone did the upload to pypi as lxc-python2, closing this.

**Comment by leonty** [comment]
Yeah, that was me actually :)
