### ISSUE TITLE
Python 2.7 bindings broke with recent Ubuntu update for liblxc1

### ISSUE THREAD

**Issue by fghaas** [lxc/python2-lxc#8]
I'm afraid the Python 2.7 bindings are broken with some recent update for liblxc1 on Ubuntu. I can't give the exact date or version when this started happening, but I know the following worked a few months ago, and now it no longer does:

```
IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import lxc

In [2]: container = lxc.Container("mycontainer")

In [3]: container.get_ips()
Segmentation fault
```

If I run the same thing in ipython3, using the in-tree Python 3 bindings, all is well.

Now I realize this is probably really low priority, but as it happens that this breakage blocks the inclusion of an otherwise very useful LXC connection plugin for Ansible; see ansible/ansible#13145 for details.

Ansible, for "reasons" explained [here](http://docs.ansible.com/ansible/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine), can't run in a Python 3-only environment. Which is silly and not lxc's problem, but if we could get this module to work again in Python 2.7, that would be a huge win.

Any thoughts on the above, @stgraber? I'd much appreciate your feedback. Thanks!

**Comment by stgraber** [comment]
Works fine here.

```
stgraber@castiana:~/Desktop$ git clone https://github.com/lxc/python2-lxc/
Cloning into 'python2-lxc'...
remote: Counting objects: 28, done.
remote: Total 28 (delta 0), reused 0 (delta 0), pack-reused 28
Unpacking objects: 100% (28/28), done.
Checking connectivity... done.

stgraber@castiana:~/Desktop$ cd python2-lxc/
stgraber@castiana:~/Desktop/python2-lxc (master)$ python setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/lxc
copying lxc/__init__.py -> build/lib.linux-x86_64-2.7/lxc
running build_ext
building '_lxc' extension
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c lxc.c -o build/temp.linux-x86_64-2.7/lxc.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/lxc.o -llxc -o build/lib.linux-x86_64-2.7/_lxc.so
stgraber@castiana:~/Desktop/python2-lxc (master)$ cd build
stgraber@castiana:~/Desktop/python2-lxc/build (master)$ cd lib.linux-x86_64-2.7/

stgraber@castiana:~/Desktop/python2-lxc/build/lib.linux-x86_64-2.7 (master)$ python
Python 2.7.11 (default, Jan 11 2016, 21:04:40) 
[GCC 5.3.1 20160112] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxc
>>> a = lxc.Container("trusty-gui")
>>> a.state
u'STOPPED'
>>> a.start()
True
>>> a.state
u'RUNNING'
>>> a.get_ips()
(u'10.0.3.220',)
>>> 
```

**Comment by stgraber** [comment]
That's running against current Ubuntu liblxc1 at version 2.0.0.beta2

**Comment by fghaas** [comment]
Weird. *That* works for me as well; what doesn't is trying to do this with the python2-lxc package from vivid (http://packages.ubuntu.com/vivid/python-lxc) against 2.0.0.beta2 from the stable PPA.

**Comment by evgeni** [comment]
That's https://bugs.launchpad.net/ubuntu/+source/python-lxc/+bug/1550912

recompilation of python-lxc in Ubuntu is enough. seems that liblxc had a short ABI break somewhere and the version in vivid is compiled against that.

**Comment by evgeni** [comment]
@fghaas this has been fixed in xenial, can you re-test?

**Comment by fghaas** [comment]
@evgeni I have my Xenial update planned for this weekend, can report back after (if I get around to it; I also have some travel scheduled).

**Comment by fghaas** [comment]
Yes, this done indeed look fixed on Xenial.
