### ISSUE TITLE
Ansible Extras support for LXC 2?

### ISSUE THREAD

**Issue by niccolox** [lxc/python2-lxc#9]
does this work for Ansible 2 on Xenial and LXC 2? 

TASK [ansible-role-lxc : Create a started container] ***************************
fatal: [arizblah.blahblah.net]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find required executable lxc-create"}

**Comment by evgeni** [comment]
I think you need to install the "lxc1" package on Xenial for Ansible to work. That's not related to python2-lxc, though :)

**Comment by stgraber** [comment]
lxc is a meta-package installing lxc1 but yeah, that error sounds like you just don't have lxc installed.

**Comment by niccolox** [comment]
sorry, shouldnt post tickets after mid-night

I have LXC 2 on Xenial

lxc --version
2.0.0

so, I guess, the Ansible Extras Module for LXC is specific to version 1

lxc-create is lxc 1

so, the Ansible module for LXC is lxc 1 only at this stage, will move along

**Comment by niccolox** [comment]
THANKS
